[project]
name = "tgindow"
version = "0.1.0"
authors = [
  { name="PyExecutor", email="belyankiss@gmail.com" },
]
description = "Библиотека для создания простых окон в телеграмм боте."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/belyankiss/TelegramWindows"
Issues = "https://github.com/belyankiss/TelegramWindows/issues"